### ISSUE TITLE
Code from v0.1.3 can't work under v0.2.0

### ISSUE THREAD

**Issue by aizcutei** [amrbashir/tauri-plugin-vibrancy#58]
Code:

```
let main_window = app.get_window("main").unwrap();

#[cfg(target_os = "macos")]
apply_vibrancy(&main_window, NSVisualEffectMaterial::FullScreenUI)
    .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");
```

Works fine with v0.1.3, but after I change to v0.2.0, the complier throw an error.

Message from complier:

```
error[E0277]: the trait bound `Window: raw_window_handle::HasRawWindowHandle` is not satisfied
   --> src/app/window.rs:16:20
    |
16  |     apply_vibrancy(&main_window, NSVisualEffectMaterial::FullScreenUI)
    |     -------------- ^^^^^^^^^^^^ the trait `raw_window_handle::HasRawWindowHandle` is not implemented for `Window`
    |     |
    |     required by a bound introduced by this call
    |
help: trait impl with same name found
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.3/src/window.rs:492:1
    |
492 | / unsafe impl<R: Runtime> raw_window_handle::HasRawWindowHandle for Window<R> {
493 | |   fn raw_window_handle(&self) -> raw_window_handle::RawWindowHandle {
494 | |     self.window.dispatcher.raw_window_handle().unwrap()
495 | |   }
496 | | }
    | |_^
    = note: perhaps two different versions of crate `raw_window_handle` are being used?
    = note: required because of the requirements on the impl of `raw_window_handle::HasRawWindowHandle` for `&Window`
note: required by a bound in `apply_vibrancy`
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/window-vibrancy-0.2.0/src/lib.rs:147:16
    |
147 |   window: impl raw_window_handle::HasRawWindowHandle,
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `apply_vibrancy`

For more information about this error, try `rustc --explain E0277`.
```

**Comment by FabianLars** [comment]
See #57, #56, and #55 :D 
This is caused by a version mismatch of the raw_window_handle crate, and will be automatically fixed with Tauri's 1.1 release.
