### ISSUE TITLE
Failed to compile with tauri 1.0.5

### ISSUE THREAD

**Issue by Yvan-xy** [amrbashir/tauri-plugin-vibrancy#60]
I tried to run the example and got this report:

```
error[E0277]: the trait bound `Window: HasRawWindowHandle` is not satisfied
   --> src/main.rs:40:22
    |
40  |       apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow)
    |       -------------- ^^^^^^^ the trait `HasRawWindowHandle` is not implemented for `Window`
    |       |
    |       required by a bound introduced by this call
    |
    = help: the trait `HasRawWindowHandle` is implemented for `&'a T`
    = note: required because of the requirements on the impl of `HasRawWindowHandle` for `&Window`
note: required by a bound in `apply_vibrancy`
   --> /Users/dyf/.cargo/registry/src/github.com-1ecc6299db9ec823/window-vibrancy-0.2.0/src/lib.rs:147:16
    |
147 |   window: impl raw_window_handle::HasRawWindowHandle,
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `apply_vibrancy`
```
source code:
```rust
fn main() {
  tauri::Builder::default()
    .setup(|app| {
      let window = app.get_window("main").unwrap();

      #[cfg(target_os = "macos")]
      apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow)
        .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");

      #[cfg(target_os = "windows")]
      apply_blur(&window, Some((18, 18, 18, 125)))
        .expect("Unsupported platform! 'apply_blur' is only supported on Windows");

      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```
rustc version: 1.59.0
tauri version: 1.0.5

**Comment by FabianLars** [comment]
See #58, #57, #56, and #55 :)
This is caused by a version mismatch of the raw_window_handle crate, and will be automatically fixed with Tauri's 1.1 release. Until then you need to downgrade window-vibrancy to 0.1.3

**Comment by Yvan-xy** [comment]
Thank you very much! Could you please tell me when shall the Tauri 1.1 be released?

**Comment by FabianLars** [comment]
It still needs a few weeks for the on-going audit.
